[package]
name = "connect4"
version = "0.1.0"
authors = ["Alexander Temper"]

[dependencies]
piston = "0.36.0"
piston2d-graphics = "0.26.0"
pistoncore-glutin_window = "0.45.0"
piston2d-opengl_graphics = "0.52.0"
